# Render configuration
services:
  - type: worker
    name: ip-checker
    runtime: docker
    repo: https://github.com/sangamsharma/get-render-ip  # Replace with your repository
    plan: starter
    envVars:
      - key: DATABASE_URL  # Optional, keep if needed for other services
        value: postgresql://postgres:[8Texas+schism]@aws-0-us-west-1.pooler.supabase.com:6543/postgres
        sync: false
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    version: "1"
